export const REFRESH_SERVICES = 'REFRESH_SERVICES';
export const REFRESH_TREATMENTS = 'REFRESH_TREATMENTS';
export const REFRESH_APPOINTMENTS = 'REFRESH_APPOINTMENTS';
export const REFRESH_USERS = 'REFRESH_USERS';
